language: erlang

env:
   - ST=Pharo-1.4 CONFIGURATION=Sample LOADS="'Core' 'Tests'" VERSION="0.8.0" REPOSITORY="github://dalehenrich/sample:configuration"
   - ST=Pharo-1.4 CONFIGURATION=Sample LOADS="'Tests'" VERSION="0.9.1" REPOSITORY="github://dalehenrich/sample:configuration"
   - ST=Squeak-4.4 CONFIGURATION=Sample LOADS="'Core' 'Tests'" VERSION="0.8.0" REPOSITORY="github://dalehenrich/sample:configuration"
   - ST=Squeak-4.4 CONFIGURATION=Sample LOADS="'Tests'" VERSION="0.9.1" REPOSITORY="github://dalehenrich/sample:configuration"

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O builderCI.zip https://github.com/dalehenrich/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd dalehenrich-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

script: $PROJECT_HOME/tests/testTravisCI.sh # -verbose
