language: erlang

env:
   - ST=Pharo-1.4 BASELINE=Sample LOADS="'ALL'" REPOSITORY="filetree://${TRAVIS_BUILD_DIR}/packages"
   - ST=Squeak-4.4 BASELINE=Sample LOADS="'ALL'" REPOSITORY="filetree://${TRAVIS_BUILD_DIR}/packages"
   - ST=GemStone-3.1.0.2 BASELINE=Sample LOADS="'ALL'" REPOSITORY="filetree://${TRAVIS_BUILD_DIR}/packages"

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O builderCI.zip https://github.com/dalehenrich/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd dalehenrich-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

script: $PROJECT_HOME/tests/testTravisCI.sh # -verbose
