language: erlang

# exclude configuration branch from builds
branches:
  except:
    - configuration

# build matrix
#   baseline, stable version and version 0.9.0
#   for Squeak4.3 and PharoCore-1.3
env:
#   - ST=Squeak4.3 TRAVIS_SCRIPT=baselineTravisCI.st
#   - ST=Squeak4.3 TRAVIS_SCRIPT=configuration090TravisCI.st
#   - ST=Squeak4.3 TRAVIS_SCRIPT=configurationStableTravisCI.st
#   - ST=PharoCore-1.3 TRAVIS_SCRIPT=baselineTravisCI.st
#   - ST=PharoCore-1.3 TRAVIS_SCRIPT=configuration090TravisCI.st
   - ST=PharoCore-1.3 TRAVIS_SCRIPT=configurationStableTravisCI.st

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -O builderCI.zip https://github.com/dalehenrich/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd dalehenrich-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

script:

   - ./build.sh -i $ST -s latAmMirror.st -m -f "$PROJECT_HOME/tests/$TRAVIS_SCRIPT" -o travisCI
   - cd "${BUILD_PATH}/travisCI/"
   - if ( test -e PharoDebug.log ); then cat PharoDebug.log; fi
   - if ( test -e PharoDebug.log ); then die; fi
   - if ( test -e TravisCISuccess.txt ); then cat TravisCISuccess.txt; fi
   - if ( test -e TravisCIFailure.txt ); then cat TravisCIFailure.txt; fi
   - if ( test -e TravisCIFailure.txt ); then die; fi
